### ISSUE TITLE
MPER

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#198]
We have MPER I-VI and MPER N.S. I-XXXIII and ongoing.

At https://github.com/papyri/idp.data/blob/master/RDF/collection.rdf#L1236-L1238 we have:

```XML
<rdf:Description rdf:about="http://papyri.info/ddbdp/mper.xiii">
    <dcterms:identifier rdf:resource="Perseus:text:1999.05.0298"/>
    <dcterms:bibliographicCitation>MPER XIII</dcterms:bibliographicCitation>
</rdf:Description>
```

How often is this used? Search for `<idno type="ddb-hybrid">mper` across HGV_meta_XML and DCLP.

The RDF only seems to apply to one file in HGV_meta_XML (there is an accompanying ddbdp file waiting to be voted through on the DDbDP board): https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV108/107414.xml#L10-L14

```XML
<idno type="filename">107414</idno>
<idno type="TM">107414</idno>
<idno type="ddb-perseus-style">0298;;6</idno>
<idno type="ddb-filename">mper.xiii.6</idno>
<idno type="ddb-hybrid">mper.xiii;;6</idno>
```

Across DCLP files we have 228 instances in 228 files of `<idno type="dclp-hybrid">mpern.s;3;16</idno>` like `dclp-hybrid` and one instance in one file of `<idno type="dclp-hybrid">mper;29;59</idno>`  (alongside what is "should" be: `<idno type="dclp-hybrid">mpern.s;29;27</idno>`)

In DCLP files we should have `<idno type="dclp-hybrid">mper.ns;3;16</idno>` 
 - so instead of `mpern.s;` => `mper.ns;`
 - `<idno type="dclp-hybrid">mper;29;59</idno>` => `<idno type="dclp-hybrid">mper.ns;29;59</idno>`

**Comment by samosafuz** [comment]
DCLP has been wrangled. It remains to update rdf with `mper.ns`; I believe we agreed that `mper.xiii` should persist and not be nested within a larger `mper` series.

**Comment by samosafuz** [comment]
But I see now that RDF has been updated to include `mper` (sc. to accommodate [987677](https://papyri.info/hgv987677)): see [a389d80](https://github.com/papyri/idp.data/commit/a389d801872e3f9b796e1bc3086ad03410eb4511). Should we nest the other entries (e.g. `mper.xiii`), then?

**Comment by samosafuz** [comment]
[107414](https://papyri.info/hgv/107414) has `<idno type="ddb-hybrid">mper.xiii;;6</idno>` and `<idno type="ddb-filename">mper.xiii.6</idno>`. These idnos are wrong: they should be `mper.ns;13;6`. There is no corresponding DDB file. 

All other instances of MPER are in DCLP, and I’ve already wrangled them in #[382](https://github.com/papyri/idp.data/pull/382). 

So, I see the following two steps as necessary: 
1. Correct the idnos in [107414](https://papyri.info/hgv/107414) to `mper.ns;13;6`
2. Delete `mper.xiii` from the RDF, since there are no other files that require it, and since we have both `mper` and `mper.ns` in RDF.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV108/107414.xml

should now be clean with https://github.com/papyri/idp.data/commit/162eaac2ef8caa4d03b7d8ce07c1e027a5ffef8b

https://github.com/papyri/idp.data/blob/master/RDF/collection.rdf

should now be clean with https://github.com/papyri/idp.data/commit/3bc4d627e5be8a70158f90901537eb57d29bda2b
